---
title: "ANALISE VENDAS SETORES"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

<link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Alegreya Sans SC' rel='stylesheet'>
<style>

.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}

P{
font:'Alegreya Sans SC';font-size: 17px;
}

h3 { 
	font-family: 'Abel';font-size: 25px;
	margin-bottom: 0; 
	font-weight: bold;
}

h4 { 
	font-family: 'Abel';font-size: 22px;
	margin-bottom: 0; 
	font-weight: bold;
	color:#8a8a8a;
}

h5 { 
	font-family: 'Abel';font-size: 20px;
	margin-bottom: 0; 
	font-weight: bold;
	color:#b5b5b5;
}
	
	
hr {
 border-top: 2px dotted grey;
}	

</style>

```{r setup, include=FALSE}
library(DBI)
library(tidyverse)
library(lubridate)
library(magrittr)
library(reshape2)
library(zoo)
con2 <- dbConnect(odbc::odbc(), "reproreplica", timeout = 10)
```



```{r,echo=FALSE}
result_day_setores <- dbGetQuery(con2,"

WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),

       CLI AS (SELECT DISTINCT C.CLICODIGO,
                       CLINOMEFANT,
                        ENDCODIGO,
                         SETOR
                          FROM CLIEN C
                           LEFT JOIN (SELECT CLICODIGO,E.ZOCODIGO,ZODESCRICAO SETOR,ENDCODIGO FROM ENDCLI E
                            LEFT JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN (20,21,22,23,24,25,26,27,28))Z ON E.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
                             WHERE CLICLIENTE='S'),

         PED AS (SELECT ID_PEDIDO,
                         P.CLICODIGO,
                          SETOR,
                           PEDDTEMIS 
                            FROM PEDID P
                             INNER JOIN FIS F ON P.FISCODIGO1=F.FISCODIGO
                              INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO AND P.ENDCODIGO=C.ENDCODIGO
                               WHERE PEDDTEMIS >= DATEADD(-30 DAY TO CURRENt_DATE ) AND PEDDTEMIS<='YESTERDAY' AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N'))

        SELECT PEDDTEMIS,
                CLICODIGO,
                 SETOR,
                  SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
                   FROM PDPRD PD
                    INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
                     GROUP BY 1,2,3")
```

```{r , echo=FALSE,message=FALSE}
result_geral <- result_day_setores %>% 
                    mutate(WKD=wday(PEDDTEMIS)) %>% 
                     filter(!WKD %in% c(1,7)) %>% 
filter(PEDDTEMIS!=as.Date('2023-01-01')) %>%
                       as.data.frame() %>% 
                         group_by(PEDDTEMIS) %>% 
                          summarize(V=sum(VRVENDA)) %>% 
                           as.data.frame() %>% 
                            mutate(MEDIAMOVEL=round(rollmeanr(V,7,fill=NA),0))  

```

```{r , echo=FALSE, fig.height=7,fig.width=12,message=FALSE,warning=FALSE}
## chart
result_geral %>% melt(id.vars="PEDDTEMIS") %>% 
  ggplot(.,aes(x=PEDDTEMIS,y=value,color=variable)) + geom_line() +
  geom_text(aes(label=format(round(value,0),big.mark=","))) +
  scale_x_datetime(date_breaks = "day",date_labels = "%d/%m") +
  theme(panel.background = element_rect(fill = "#0c1839"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(colour = "#15295f"),
        legend.position = "top") + scale_colour_manual(values = c("#5783ad", "#00ffff")) +
        labs(title = "GERAL") +
        xlab("EMISSÃO") + ylab("VENDAS")
```


```{r , echo=FALSE,message=FALSE}
result_setor1 <- result_day_setores %>% 
                    mutate(WKD=wday(PEDDTEMIS)) %>% 
                     filter(!WKD %in% c(1,7)) %>% 
filter(PEDDTEMIS!=as.Date('2023-01-01')) %>% 
                        as.data.frame() %>% 
                         filter(SETOR=='SETOR 1 - FLORIANOPOLIS REDES') %>% 
                          group_by(PEDDTEMIS) %>% 
                           summarize(V=sum(VRVENDA)) %>% 
                            as.data.frame() %>% 
                             mutate(MEDIAMOVEL=round(rollmeanr(V,7,fill=NA),0))  

```

```{r , echo=FALSE, fig.height=7,fig.width=12,message=FALSE,warning=FALSE}
## chart
result_setor1 %>% melt(id.vars="PEDDTEMIS") %>% 
  ggplot(.,aes(x=PEDDTEMIS,y=value,color=variable)) + geom_line() +
  geom_text(aes(label=format(round(value,0),big.mark=","))) +
  scale_x_datetime(date_breaks = "day",date_labels = "%d/%m") +
  theme(panel.background = element_rect(fill = "#0c1839"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(colour = "#15295f"),
        legend.position = "top") + scale_colour_manual(values = c("#5783ad", "#00ffff")) +
        labs(title = "SETOR 1") +
        xlab("EMISSÃO") + ylab("VENDAS")
```


<hr>

```{r , echo=FALSE,message=FALSE,warning=FALSE}
result_setor2 <- result_day_setores %>% 
                    mutate(WKD=wday(PEDDTEMIS)) %>% 
                     filter(!WKD %in% c(1,7)) %>% 
filter(PEDDTEMIS!=as.Date('2023-01-01')) %>%
  as.data.frame() %>% 
                      filter(SETOR=='SETOR 2 - CRICIUMA - SUL') %>% 
                      group_by(PEDDTEMIS) %>% 
                       summarize(V=sum(VRVENDA)) %>% 
                        as.data.frame() %>% 
                         mutate(MEDIAMOVEL=round(rollmeanr(V,7,fill=NA),0))  

```

```{r , echo=FALSE, fig.height=7,fig.width=12,message=FALSE,warning=FALSE}
## chart
result_setor2 %>% melt(id.vars="PEDDTEMIS") %>% 
  ggplot(.,aes(x=PEDDTEMIS,y=value,color=variable)) + geom_line() +
  geom_text(aes(label=format(round(value,0),big.mark=","))) +
  scale_x_datetime(date_breaks = "day",date_labels = "%d/%m") +
  theme(panel.background = element_rect(fill = "#0c1839"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(colour = "#15295f"),
        legend.position = "top") + scale_colour_manual(values = c("#5783ad", "#00ffff")) +
        labs(title = "SETOR 2") +
        xlab("EMISSÃO") + ylab("VENDAS")
```

<hr>

```{r , echo=FALSE,message=FALSE,warning=FALSE}
result_setor3 <- result_day_setores %>% 
                    mutate(WKD=wday(PEDDTEMIS)) %>% 
                     filter(!WKD %in% c(1,7)) %>% 
filter(PEDDTEMIS!=as.Date('2023-01-01')) %>%
  as.data.frame() %>% 
                      filter(SETOR=='SETOR 3 - CHAPECO - OESTE - RS') %>% 
                      group_by(PEDDTEMIS) %>% 
                       summarize(V=sum(VRVENDA)) %>% 
                        as.data.frame() %>% 
                         mutate(MEDIAMOVEL=round(rollmeanr(V,7,fill=NA),0))  

```

```{r , echo=FALSE, fig.height=7,fig.width=12,message=FALSE,warning=FALSE}
## chart
result_setor3 %>% melt(id.vars="PEDDTEMIS") %>% 
  ggplot(.,aes(x=PEDDTEMIS,y=value,color=variable)) + geom_line() +
  geom_text(aes(label=format(round(value,0),big.mark=","))) +
  scale_x_datetime(date_breaks = "day",date_labels = "%d/%m") +
  theme(panel.background = element_rect(fill = "#0c1839"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(colour = "#15295f"),
        legend.position = "top") + scale_colour_manual(values = c("#5783ad", "#00ffff")) +
        labs(title = "SETOR 3") +
        xlab("EMISSÃO") + ylab("VENDAS")
```


<hr>

```{r , echo=FALSE,message=FALSE,warning=FALSE}
result_setor4 <- result_day_setores %>% 
                    mutate(WKD=wday(PEDDTEMIS)) %>% 
                     filter(!WKD %in% c(1,7)) %>%
filter(PEDDTEMIS!=as.Date('2023-01-01')) %>%
  as.data.frame() %>% 
                      filter(SETOR=='SETOR 4 - JOINVILLE - NORTE') %>% 
                      group_by(PEDDTEMIS) %>% 
                       summarize(V=sum(VRVENDA)) %>% 
                        as.data.frame() %>% 
                         mutate(MEDIAMOVEL=round(rollmeanr(V,7,fill=NA),0))  

```

```{r , echo=FALSE, fig.height=7,fig.width=12,message=FALSE,warning=FALSE}
## chart
result_setor4 %>% melt(id.vars="PEDDTEMIS") %>% 
  ggplot(.,aes(x=PEDDTEMIS,y=value,color=variable)) + geom_line() +
  geom_text(aes(label=format(round(value,0),big.mark=","))) +
  scale_x_datetime(date_breaks = "day",date_labels = "%d/%m") +
  theme(panel.background = element_rect(fill = "#0c1839"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(colour = "#15295f"),
        legend.position = "top") + scale_colour_manual(values = c("#5783ad", "#00ffff")) +
        labs(title = "SETOR 4") +
        xlab("EMISSÃO") + ylab("VENDAS")
```



<hr>

```{r , echo=FALSE,message=FALSE,warning=FALSE}
result_setor5 <- result_day_setores %>% 
                    mutate(WKD=wday(PEDDTEMIS)) %>% 
                     filter(!WKD %in% c(1,7)) %>% 
filter(PEDDTEMIS!=as.Date('2023-01-01')) %>% 
  as.data.frame() %>% 
                      filter(SETOR=='SETOR 5 - BLUMENAU - VALE') %>% 
                      group_by(PEDDTEMIS) %>% 
                       summarize(V=sum(VRVENDA)) %>% 
                        as.data.frame() %>% 
                         mutate(MEDIAMOVEL=round(rollmeanr(V,7,fill=NA),0))  

```

```{r , echo=FALSE, fig.height=7,fig.width=12,message=FALSE,warning=FALSE}
## chart
result_setor5 %>% melt(id.vars="PEDDTEMIS") %>% 
  ggplot(.,aes(x=PEDDTEMIS,y=value,color=variable)) + geom_line() +
  geom_text(aes(label=format(round(value,0),big.mark=","))) +
  scale_x_datetime(date_breaks = "day",date_labels = "%d/%m") +
  theme(panel.background = element_rect(fill = "#0c1839"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(colour = "#15295f"),
        legend.position = "top") + scale_colour_manual(values = c("#5783ad", "#00ffff")) +
        labs(title = "SETOR 5") +
        xlab("EMISSÃO") + ylab("VENDAS")
```



<hr>

```{r , echo=FALSE,message=FALSE,warning=FALSE}
result_setor6 <- result_day_setores %>% 
                    mutate(WKD=wday(PEDDTEMIS)) %>% 
                     filter(!WKD %in% c(1,7)) %>% 
filter(PEDDTEMIS!=as.Date('2023-01-01')) %>%
  as.data.frame() %>% 
                      filter(SETOR=='SETOR 6 - B CAMBORIU - LITORAL') %>% 
                      group_by(PEDDTEMIS) %>% 
                       summarize(V=sum(VRVENDA)) %>% 
                        as.data.frame() %>% 
                         mutate(MEDIAMOVEL=round(rollmeanr(V,7,fill=NA),0))  

```

```{r , echo=FALSE, fig.height=7,fig.width=12,message=FALSE,warning=FALSE}
## chart
result_setor6 %>% melt(id.vars="PEDDTEMIS") %>% 
  ggplot(.,aes(x=PEDDTEMIS,y=value,color=variable)) + geom_line() +
  geom_text(aes(label=format(round(value,0),big.mark=","))) +
  scale_x_datetime(date_breaks = "day",date_labels = "%d/%m") +
  theme(panel.background = element_rect(fill = "#0c1839"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(colour = "#15295f"),
        legend.position = "top") + scale_colour_manual(values = c("#5783ad", "#00ffff")) +
        labs(title = "SETOR 6") +
        xlab("EMISSÃO") + ylab("VENDAS")
```


<hr>

```{r , echo=FALSE,message=FALSE,warning=FALSE}
result_setor7 <- result_day_setores %>% 
                    mutate(WKD=wday(PEDDTEMIS)) %>% 
                     filter(!WKD %in% c(1,7)) %>% 
 filter(PEDDTEMIS!=as.Date('2023-01-01')) %>%                          
  as.data.frame() %>% 
                      filter(SETOR=='SETOR 7 - FLORIANOPOLIS  LOJAS') %>% 
                      group_by(PEDDTEMIS) %>% 
                       summarize(V=sum(VRVENDA)) %>% 
                        as.data.frame() %>% 
                         mutate(MEDIAMOVEL=round(rollmeanr(V,7,fill=NA),0))  

```

```{r , echo=FALSE, fig.height=7,fig.width=12,message=FALSE,warning=FALSE}
## chart
result_setor7 %>% melt(id.vars="PEDDTEMIS") %>% 
  ggplot(.,aes(x=PEDDTEMIS,y=value,color=variable)) + geom_line() +
  geom_text(aes(label=format(round(value,0),big.mark=","))) +
  scale_x_datetime(date_breaks = "day",date_labels = "%d/%m") +
  theme(panel.background = element_rect(fill = "#0c1839"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(colour = "#15295f"),
        legend.position = "top") + scale_colour_manual(values = c("#5783ad", "#00ffff")) +
        labs(title = "SETOR 7") +
        xlab("EMISSÃO") + ylab("VENDAS")
```


<hr>

```{r , echo=FALSE,message=FALSE,warning=FALSE}
result_setor8 <- result_day_setores %>% 
                    mutate(WKD=wday(PEDDTEMIS)) %>% 
                     filter(!WKD %in% c(1,7)) %>% 
 filter(PEDDTEMIS!=as.Date('2023-01-01')) %>%                          
  as.data.frame() %>% 
                      filter(SETOR=='SETOR 8 - JOACABA - MEIO OESTE') %>% 
                      group_by(PEDDTEMIS) %>% 
                       summarize(V=sum(VRVENDA)) %>% 
                        as.data.frame() %>% 
                         mutate(MEDIAMOVEL=round(rollmeanr(V,7,fill=NA),0))  

```

```{r , echo=FALSE, fig.height=7,fig.width=12,message=FALSE,warning=FALSE}
## chart
result_setor8 %>% melt(id.vars="PEDDTEMIS") %>% 
  ggplot(.,aes(x=PEDDTEMIS,y=value,color=variable)) + geom_line() +
  geom_text(aes(label=format(round(value,0),big.mark=","))) +
  scale_x_datetime(date_breaks = "day",date_labels = "%d/%m") +
  theme(panel.background = element_rect(fill = "#0c1839"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(colour = "#15295f"),
        legend.position = "top") + scale_colour_manual(values = c("#5783ad", "#00ffff")) +
        labs(title = "SETOR 8") +
        xlab("EMISSÃO") + ylab("VENDAS")
```


<hr>

```{r , echo=FALSE,message=FALSE,warning=FALSE}
result_setor9 <- result_day_setores %>% 
                    mutate(WKD=wday(PEDDTEMIS)) %>% 
                     filter(!WKD %in% c(1,7)) %>% 
 filter(PEDDTEMIS!=as.Date('2023-01-01')) %>%                          
  as.data.frame() %>% 
                      filter(SETOR=='SETOR 9 - ZONA NEUTRA') %>% 
                      group_by(PEDDTEMIS) %>% 
                       summarize(V=sum(VRVENDA)) %>% 
                        as.data.frame() %>% 
                         mutate(MEDIAMOVEL=round(rollmeanr(V,7,fill=NA),0))  

```

```{r , echo=FALSE, fig.height=7,fig.width=12,message=FALSE,warning=FALSE}
## chart
result_setor9 %>% melt(id.vars="PEDDTEMIS") %>% 
  ggplot(.,aes(x=PEDDTEMIS,y=value,color=variable)) + geom_line() +
  geom_text(aes(label=format(round(value,0),big.mark=","))) +
  scale_x_datetime(date_breaks = "day",date_labels = "%d/%m") +
  theme(panel.background = element_rect(fill = "#0c1839"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(colour = "#15295f"),
        legend.position = "top") + scale_colour_manual(values = c("#5783ad", "#00ffff")) +
        labs(title = "SETOR 9") +
        xlab("EMISSÃO") + ylab("VENDAS")
```